name: environment
channels:
  - conda-forge
dependencies:
  - python>3.8
  - numpy
  - pip
  - pip:
    - xarray
    - matplotlib
    - cftime
    - cfgrib
    - eccodes
    - wrf
    - scipy
    - cartopy
    - siphon
    - metpy
    - pandas
